### ISSUE TITLE
Provider returned Incorrect Fee values 

### ISSUE THREAD

**Issue by talhamalik883** [bcnmy/biconomy-client-sdk#139]
In client-sdk **provider.getFeeData()** function is called to populate **maxFeePerGas** and **maxPriorityFeePerGas** for any userOp created in client-sdk. The fee values returned by **getFeeData** are either null or low as compared to on chain network fee. This can be sorted by switching from provider to an external api that send's accurate data. Following are the requirements for external endpoint for fetching fee values.

```
Url: BASE_URL/gas-prices/chainid
Type: GET
params: chainid
```
**Response**

```
{
code: 200,
message: 'SUCCESS',
data: {
gasPrice: 10,
maxFeePerGas: 12,
maxPriorityFeePerGas: 2
}
}
```

**Comment by tomarsachin2271** [comment]
Instead of adding a new end point on bundler, we can use the same bundler end point and pass the request parameters in form of [JSON RPC Request](https://www.jsonrpc.org/specification)


Url: Bundler URL
Type: GET
Params: 
```
{
	"method": "eth_getUserOpGasPrices",
	"params": ["<Chain_ID_Value"],
	"jsonrpc": "2.0",
	"id": 1
}
```


**Success Response**
```
{
	"jsonrpc": "2.0",
	"id": 1,
        "result" : {
            "maxFeePerGas": "0x987239",
            "maxPriorityFeePerGas": "0x86bac3"
        }
}
```

**Error Response**
```
{
	"jsonrpc": "2.0",
	"id": 1,
        "error" : {
            "code": <Integer value>,
            "message" : "String error message",
            "data": {}. // Any data related to error
        }
}
```

**Comment by talhamalik883** [comment]
> Instead of adding a new end point on bundler, we can use the same bundler end point and pass the request parameters in form of [JSON RPC Request](https://www.jsonrpc.org/specification)
> 
> Url: Bundler URL Type: GET Params:
> 
> ```
> {
> 	"method": "eth_getUserOpGasPrices",
> 	"params": ["<Chain_ID_Value"],
> 	"jsonrpc": "2.0",
> 	"id": 1
> }
> ```
> 
> **Success Response**
> 
> ```
> {
> 	"jsonrpc": "2.0",
> 	"id": 1,
>         "result" : {
>             "maxFeePerGas": "0x987239",
>             "maxPriorityFeePerGas": "0x86bac3"
>         }
> }
> ```
> 
> **Error Response**
> 
> ```
> {
> 	"jsonrpc": "2.0",
> 	"id": 1,
>         "error" : {
>             "code": <Integer value>,
>             "message" : "String error message",
>             "data": {}. // Any data related to error
>         }
> }
> ```

yeah that sounds good. Can we add gasPrice another attribute also in response ? Some chains do not support type 2 transaction so we will just use gasPrice in that case.

**Comment by tomarsachin2271** [comment]
For those who don't support type 2, value of maxFeePerGas and maxPriorityFeePerGas value will be same in this case. This is mentioned in the ERC-4337 as well, as UserOp doesn't have gasPrice field.

**Comment by tomarsachin2271** [comment]
You can check how EntryPoint handles this case here https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/core/EntryPoint.sol#L593

**Comment by talhamalik883** [comment]
> field

using gasPrice meant that i will assign gasPrice to **maxFee** and **maxPriorityFee** for chains that don't support type 2. 

```
      const { maxFeePerGas,  maxPriorityFeePerGas, gasPrice } = await this.provider.getGasPrices()
        userOp.maxFeePerGas = maxFeePerGas ?? gasPrice
        userOp.maxPriorityFeePerGas = maxPriorityFeePerGas ?? gasPrice
    }
```

**Comment by livingrockrises** [comment]
https://github.com/bcnmy/biconomy-client-sdk/pull/143
