### ISSUE TITLE
@biconomyyour hyphen STEALING ? Bridging in progress...  Unable to confirm receipt of this transaction. Please contact us if you have not received your funds.

### ISSUE THREAD

**Issue by EDOARDOFD** [bcnmy/biconomy-client-sdk#162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EDOARDOFD** [comment]
@biconomyyour hyphen STEALING ? Bridging in progress...

Unable to confirm receipt of this transaction. Please contact us if you have not received your funds.

**Comment by AmanRaj1608** [comment]
Can you ask this on discord, this package is not related to hyphen.
