### ISSUE TITLE
Error in bundling sdk in another typescript library

### ISSUE THREAD

**Issue by cardosofelipe** [bcnmy/biconomy-client-sdk#197]
**Describe the bug**
When building my library with bundled biconomy sdk I get the following error:
node_modules/@biconomy/core-types/dist/src/AccountAbstractionTypes.d.ts:1:52 - error TS2307: Cannot find module 'Types' or its corresponding type declarations.

**To Reproduce**
1. Install @biconomy/smart-account 
2. Build typescript lib with tsc
3. See error

**Expected behavior**
Successful build

**Desktop:**
 - OS: Linux Mint 20.3 Cinnamon

**Additional context**
It seems that the error is caused by a wrong import in the file AccountAbstractionTypes.d.ts. 
Currently the import is:
import { FallbackApiResponse, UserOperation } from 'Types';

It should be as follows:
import { FallbackApiResponse, UserOperation } from './Types';

**Comment by AmanRaj1608** [comment]
What's the version of the `@biconomy/smart-account`?
Can you try using 2.0.2

**Comment by cardosofelipe** [comment]
> What's the version of the `@biconomy/smart-account`? Can you try using 2.0.2

I am using precisely this version. For now I have to manualy change the file  AccountAbstractionTypes.d.ts in node_modules.
Obviously it is not a proper fix, should I open a PR ? The fix is simply the one I mentioned in my first comment.
