### ISSUE TITLE
No way to override gas limit when the wallet is not deployed

### ISSUE THREAD

**Issue by jainkunal** [bcnmy/biconomy-client-sdk#225]
There is no way of specifying gas limit on transactions when the wallet is not deployed.

`sendTransaction` and `sendTransactionBatch` ignore the gasLimit set in the transaction when the wallet is not deployed.
Following the callpath
[createSignedUserOp](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/account-abstraction/src/BaseAccountAPI.ts#L359C9-L359C27) -> [createUnsignedUserOp](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/account-abstraction/src/SmartAccountAPI.ts#L187) -> [encodeUserOpCallDataAndGasLimit](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/account-abstraction/src/BaseAccountAPI.ts#L359C9-L359C27)

it seems that `encodeUserOpCallDataAndGasLimit` ignores `gasLimit` set in the `detailsForUserOp` and sets `600000` as default `callGasLimit`.
https://github.com/bcnmy/biconomy-client-sdk/blob/737634190a689b9dde77105aa717fc8ee3136223/packages/account-abstraction/src/BaseAccountAPI.ts#L261-L272
As a practice it would be great if the transaction gasLimit is used as the transaction builder may have more data about the gasLimit rather than a default number.

On top of this `sendTransactionBatch` ignores any gasLimit set on the transaction and doesn't send it down the call path as mentioned in #199.

**Comment by livingrockrises** [comment]
which version of the sdk you're using?

**Comment by livingrockrises** [comment]
can you share more information about how you're trying to override it?
estimating callGasLimit has been tricky in the case of account is not deployed. we have now updated gas limit calc logic in the bundler which accurately estimates callGasLimit for undeployed accounts as well.

**Comment by jainkunal** [comment]
The issue was created when trying v2.

Now I am trying v3 of the SDK and running into #236.
Tried overriding the callGasLimit but that also doesn't work
```
partialUserOp = await account.estimateUserOpGas(partialUserOp, { callGasLimit: 2000000 });
```
The response still has the negative valued callGasLimit.
```
	"callGasLimit": -3475944,
```

**Comment by livingrockrises** [comment]
Hi, please share the chain id.
Can you also remove maxFeePerGas and maxPriorityFeePerGas keys (or make them 0) in partialUserOp and call estimation API.
meanwhile fix for #236 is WIP

**Comment by jainkunal** [comment]
I am doing this on Arbitrum.

Removing maxFeePerGas and maxPriorityFeePerGas keys also doesn't help. The only thing that helps is setting `skipBundlerGasEstimation` to true but then I have to specify all other params like preVerificationGas, verificationGasLimit and others which I don't really want to.

overrides when doing `partialUserOp = await account.buildUserOp(partialUserOp, { callGasLimit: 2000000 });` also don't work

**Comment by livingrockrises** [comment]
can you please log your partial userop here

**Comment by livingrockrises** [comment]
please upgrade to package versions 3.1.0-alpha.0
