### ISSUE TITLE
Typing error on `getPaymasterAndData`

### ISSUE THREAD

**Issue by dysbulic** [bcnmy/biconomy-client-sdk#303]
The [TypeScript definition for `getPaymasterAndData`](//github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/interfaces/IPaymaster.ts#L6) only takes one argument, but the [actual function](//github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/BiconomyPaymaster.ts#L254-L257) takes two.

To get it to work I have to do:
```typescript
const { paymasterAndData } = await (
  account.paymaster.getPaymasterAndData as (
    op: Partial<UserOperation>,
    service: SponsorUserOperationDto,
  ) => Promise<PaymasterAndDataResponse>
)(partialUserOp, paymasterServiceData)
```

**Comment by livingrockrises** [comment]
> The [TypeScript definition for `getPaymasterAndData`](//github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/interfaces/IPaymaster.ts#L6) only takes one argument, but the [actual function](//github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/BiconomyPaymaster.ts#L254-L257) takes two.
> 
> To get it to work I have to do:
> 
> ```ts
> const { paymasterAndData } = await (
>   account.paymaster.getPaymasterAndData as (
>     op: Partial<UserOperation>,
>     service: SponsorUserOperationDto,
>   ) => Promise<PaymasterAndDataResponse>
> )(partialUserOp, paymasterServiceData)
> ```

the [actual function](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/BiconomyPaymaster.ts#L254-L257) from BiconomyPaymaster class which implements [IHybridPaymaster](https://github.com/bcnmy/biconomy-client-sdk/blob/master/packages/paymaster/src/interfaces/IHybridPaymaster.ts) which in turn implements IPaymaster. 

so it depends on the type of paymaster supplied to account during initialisation.
