### ISSUE TITLE
`UserOpResponse.wait` does not wait for enough confirmations

### ISSUE THREAD

**Issue by au2001** [bcnmy/biconomy-client-sdk#373]
## Problem You're Facing

After sending a userOp, I want to wait for N confirmations on the blockchain.\
Right now, using `userOpResponse.wait(999)` returns a Promise which resolves right after the transaction is included in a block, without waiting for any additional confirmation.

## Proposed Solution

The `UserOpResponse.wait` function already takes as argument the number of desired confirmations.\
That function should simply be fixed to correctly take into account this value.

## Alternatives Considered

A possible workaround is to use `waitForTxHash` and wait for the desired number of confirmations for that transaction using another library (e.g. ethers).

## Use Cases

Waiting for a given number of confirmations can help prevent issues with blockchain forks/reorgs.

## Additional Info

I'm willing to provide a fix and will open a PR which closes this issue.

**Comment by livingrockrises** [comment]
we will look into this and also review the PR
