### ISSUE TITLE
The @biconomy/web3-auth does not work with next.js

### ISSUE THREAD

**Issue by dishant0406** [bcnmy/biconomy-client-sdk#75]
**Describe the bug**
The @biconomy/web3-auth does not work with next.js.
Importing the social login gives error with the styles

**To Reproduce**
1. Import the socialLogin
2. It is not working with nextjs 

**Expected behavior**
It should work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/90952604/202191094-1a3cffec-a099-4ced-84f2-2ec55d7ecdeb.png)

**Comment by asheerrizvi** [comment]
thanks for opening this @dishant0406, we will have a look. Seems like a [Next.js quirk](https://github.com/vercel/next.js/issues/19936) but we will see if we can come up with an alternative.

**Comment by pythonpete32** [comment]
not a fix for the problem but you can just use use web3Auth directly, I have just added it in this boilerplate https://github.com/pythonpete32/hack-web3-boilerplate/blob/main/ui/lib/wagmiClient.ts

**Comment by asheerrizvi** [comment]
@dishant0406 I think you can use this while we are trying to come up with a better solution

https://github.com/bem/next-global-css

**Comment by AmanRaj1608** [comment]
This issue is fixed now. Can check out working example code here https://github.com/bcnmy/sdk-examples/tree/master/nextjs-biconomy-web3Auth
