### ISSUE TITLE
Getting TypeError while importing Smart Account in React app 

### ISSUE THREAD

**Issue by livingrockrises** [bcnmy/biconomy-client-sdk#83]
**Describe the bug**

The app starts failing after write
import SmartAccount from "@biconomy/smart-account"
<img width="1078" alt="Screenshot 2022-11-27 at 12 03 26 AM" src="https://user-images.githubusercontent.com/90545960/204369181-8ba28b7d-6663-4ad0-a86c-1b5c7cb33e02.png">

[TypeError: Class extends value undefined is not a constructor or null]

**To Reproduce**
1. Go to https://github.com/bcnmy/biconomy-sdk-starter-kit
2. Check js/src/App.js or typescript/src/App.tsx
3. import SmartAccount and create an instance new SmartAccount(provider, options)
4. yarn start
5. Front end fails to load with above error

```
at ./node_modules/messaging-sdk/node_modules/ws/lib/receiver.js (receiver.js:27:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/messaging-sdk/node_modules/ws/lib/websocket.js (websocket.js:15:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/messaging-sdk/node_modules/ws/index.js (index.js:3:1)
    at options.factory (react refresh:6:1)
```

**Expected behavior**
Smart Account should get initialised properly

**Screenshots**
attached above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos monterey
 - Browser [e.g. chrome, safari] chrome
 
 node v16.14.2
 

**Additional context**
Import fails for js file

**Comment by livingrockrises** [comment]
I am checking this
https://tinyurl.com/2s3fvk7y
there is possibly a circular dependency?

**Comment by livingrockrises** [comment]
for js this below import works but still facing above issue

`const SmartAccount = require("@biconomy/smart-account").default; `

**Comment by AmanRaj1608** [comment]
This might come when you have not configured the ws lib in webpack properly.

For react applications can add `stream-browserify` in webpack file
For Next.js applications add `stream-browserify` in `next.config.js`

```js
"stream": require.resolve("stream-browserify"),
```

**Comment by livingrockrises** [comment]
something like this what's done in gasless playground?

https://github.com/bcnmy/gasless-playground/pull/1/files
