### ISSUE TITLE
Webpack 5 breaking changes :: SDK not working due to polyfills

### ISSUE THREAD

**Issue by livingrockrises** [bcnmy/biconomy-client-sdk#87]
**Describe the bug**
The React demo App using biconomy SDK does not start

I am using below in my package.json
 "start": "react-scripts start"

**To Reproduce**
1. Import below packages in react app

    "@biconomy/core-types": "0.0.2",
    "@biconomy/relayer": "0.0.2",
    "@biconomy/smart-account": "0.0.2",
    "@biconomy/transactions": "0.0.2",
    "@biconomy/web3-auth": "0.0.2",
    
2. Start the App

**Expected behavior**
Should be able to run in the browser with sdk and it's dependencies

**Screenshots**
<img width="1343" alt="Screenshot 2022-11-29 at 3 06 20 AM" src="https://user-images.githubusercontent.com/90545960/204386380-a170955b-b339-452e-a0aa-a7c23b1fbf80.png">
<img width="776" alt="Screenshot 2022-11-29 at 3 06 41 AM" src="https://user-images.githubusercontent.com/90545960/204386401-0165f709-e695-4592-964c-10f5f1627591.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Macos monterey
 - Browser [e.g. chrome, safari] chrome

**Additional context**

What I suspect is that because the Biconomy SDK is using @biconomy/messaging-sdk and @toruslabs has dependencies that rely on core node modules such as aqmplib, stream, zlib, therefore it does not work on client side. webpack 5 does not have these polyfills by default. 
I am also gettng below for path, fs, tls 

`Module not found: Error: Can't resolve 'path' in '/Users/chirag/work/biconomy/scw-playground/sdk-demo/node_modules/node-gyp-build'`

**Comment by AmanRaj1608** [comment]
Yeah so after webpack version >=5, NodeJS polyfills are not included and user have to configure the webpack themselves. 

The first solution decrease the webpack version from 5 to 4, for example in react use react-scripts: 4, in nextjs use version 12. But this is not recommended.

The best solution is to configure the webpack on client side. 

- For react CRA applications can create `config-overrides.js` file.
```bash
yarn add -D crypto-browserify stream-browserify  url browserify-zlib stream-http https-browserify assert os-browserify path-browserify process react-app-rewired
```
```js
const webpack = require('webpack');

module.exports = function override(config) {
    const fallback = config.resolve.fallback || {};
    Object.assign(fallback, {
        "fs": false,
        "net": false,
        "tls": false,
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify"),
        "url": require.resolve("url"),
        "zlib": require.resolve("browserify-zlib"),
        "http": require.resolve("stream-http"),
        "https": require.resolve("https-browserify"),
        "assert": require.resolve("assert"),
        "os": require.resolve("os-browserify"),
        "path": require.resolve("path-browserify"),
        "process/browser": require.resolve("process/browser"),
    })
    config.resolve.fallback = fallback;
    config.plugins = (config.plugins || []).concat([
        new webpack.ProvidePlugin({
            process: 'process/browser',
            Buffer: ['buffer', 'Buffer']
        })
    ])
    config.ignoreWarnings = [/Failed to parse source map/];
    return config;
}
```


- For Next.js applications will have to create `next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        "fs": false,
        "net": false,
        "tls": false,
        "crypto": require.resolve("crypto-browserify"),
        "stream": require.resolve("stream-browserify"),
        "url": require.resolve("url"),
        "zlib": require.resolve("browserify-zlib"),
        "http": require.resolve("stream-http"),
        "https": require.resolve("https-browserify"),
        "assert": require.resolve("assert"),
        "os": require.resolve("os-browserify"),
        "path": require.resolve("path-browserify"),
        "process/browser": require.resolve("process/browser"),
      };
    }
    return config;
  },
};

module.exports = nextConfig;
```

More info about polyfills error
- https://github.com/web3/web3.js#troubleshooting-and-known-issues
- https://stackoverflow.com/a/64802753
